### PR TITLE
Merge Preparator 

### PR DESCRIPTION
**Pull request by sirexeclp**

### CODE REVIEW

**Comment by sirexeclp** [comment]
To address the elephant in the room, the benkeKarsch dataset is to big for git-hub and since in missing in the repo, thats why our tests fail.
We also noticed that we included some files in our pr, that you might not want to pull.
I don't know if you can cherry pick from the pr or if we had to do this, then we would make an other pr.

We did not have the time between exams to implement the proposed hypothesis test, because it was 
more complicated than we initially thought. We also didn't find a nice statistical library that would do the job.

We noticed two things in the execution engine that might need to change or at least be discussed:

First when testing our applicability function, it received all the rows, which when using the benkeKarsch dataset, made it impossible to run though. If I recall correctly it was stated that the callAP function would only receive a sample of the dataset.

Secondly, the decision engine in its current state trys combinations of columns (this was hard coded to 1, don't know if it changed since), but only in order. For our merge-date function it would be required to have all permutations of 3 columns as well. We thought that generating the permutations would fit better into the execution engine then in our code, since its functionality is closely related to what it now does. It might be good thought to only enable it for preparators that require it.

**Comment by lanchiang** [comment]
Thank you for your two suggestions to improve the decision engine. I just saw that now, so sorry for the late reply.
For point 2, do you mean the permutation should or should not be in the decision engine? Now it's in the decision engine because I think calApplicability function only needs to operate on a column subset each time. Therefore, the decision engine generates all the permutation and then pass it as a parameter to calApplicability.

**Comment by lanchiang** [comment]
I think MergePreparator should not also do delete columns that are being used to merge. DeleteProperty should be dedicated to this function.

**Comment by sirexeclp** [comment]
> Now it's in the decision engine because I think calApplicability function only needs to operate on a column subset each time. Therefore, the decision engine generates all the permutation and then pass it as a parameter to calApplicability.

Permutations **should** be in the decision engine, but at the time we made the pr, they weren't, or did not work correctly. To make it more clear here an example:

We have the rows `ABCD`
the decision engine will now try all combinations of 3:

`ABC`
`BCD`
...
But it did not seem to try all permutations of  `ABC`:
`ABC`
`ACB`
`BAC`
`BCA`
`CAB`
`CBA`

Meaning for us the order of columns is significant and every set of 3 columns needs to be passed 6 times in all 6 permutations.


> I think MergePreparator should not also do delete columns that are being used to merge. DeleteProperty should be dedicated to this function.

I must agree with you on that one. It should be an easy fix, though.

**Comment by lanchiang** [comment]
I see. Now the decision engine should work as you expect. Plus I will fix this problem. Thanks!

**Pull request merged**
